using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Rotate a cylinder around the x and z axes. Switch from one to the other
// when the rotation in the current axis reaches 360 degrees.
public class CylinderRotation : MonoBehaviour
{
	private float x;
	private float z;
	private bool rotateX;
	private float rotationSpeed;

	void Start()
	{
		x = 0.0f;
		z = 0.0f;
		rotateX = true;
		rotationSpeed = 75.0f;
	}

	void Update()
	{
		if (rotateX == true)
		{
			x += Time.deltaTime * rotationSpeed;

			if (x > 360.0f)
			{
				x = 0.0f;
				rotateX = false;
			}
		}
		else
		{
			z += Time.deltaTime * rotationSpeed;

			if (z > 360.0f)
			{
				z = 0.0f;
				rotateX = true;
			}
		}

		transform.localRotation = Quaternion.Euler(x, 0, z);
	}
}
